import json
from pathlib import Path
from app.services.food_importer import FoodImporter

def generate_catalog_migration():
    data_path = Path(__file__).resolve().parent.parent.parent / "data" / "seed_foods.json"
    foods = FoodImporter.load_and_normalize_dataset(data_path)
    
    sql = []
    sql.append("-- ===========================================================================")
    sql.append("-- Calzy Migration 003: Create Food Catalog, Nutrition & Servings Schema")
    sql.append("-- Authoritative data sources: USDA FoodData Central & ICMR-NIN IFCT 2017")
    sql.append("-- ===========================================================================")
    sql.append("")
    sql.append("-- 1. Create foods table")
    sql.append("CREATE TABLE IF NOT EXISTS public.foods (")
    sql.append("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    sql.append("    name TEXT NOT NULL,")
    sql.append("    category TEXT NOT NULL,")
    sql.append("    source TEXT NOT NULL,")
    sql.append("    external_id TEXT UNIQUE NOT NULL,")
    sql.append("    brand TEXT DEFAULT NULL,")
    sql.append("    default_unit TEXT NOT NULL DEFAULT 'portion',")
    sql.append("    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),")
    sql.append("    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()")
    sql.append(");")
    sql.append("")
    sql.append("-- 2. Create food_nutrition table (Strict 100g basis)")
    sql.append("CREATE TABLE IF NOT EXISTS public.food_nutrition (")
    sql.append("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    sql.append("    food_id UUID NOT NULL REFERENCES public.foods(id) ON DELETE CASCADE,")
    sql.append("    basis_grams NUMERIC NOT NULL DEFAULT 100.0,")
    sql.append("    calories NUMERIC NOT NULL,")
    sql.append("    protein_g NUMERIC NOT NULL,")
    sql.append("    carbs_g NUMERIC NOT NULL,")
    sql.append("    fat_g NUMERIC NOT NULL,")
    sql.append("    fiber_g NUMERIC NOT NULL DEFAULT 0.0,")
    sql.append("    sugar_g NUMERIC NOT NULL DEFAULT 0.0,")
    sql.append("    sodium_mg NUMERIC NOT NULL DEFAULT 0.0,")
    sql.append("    micronutrients JSONB NOT NULL DEFAULT '{}'::jsonb,")
    sql.append("    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),")
    sql.append("    CONSTRAINT uq_food_nutrition_food_id UNIQUE (food_id)")
    sql.append(");")
    sql.append("")
    sql.append("-- 3. Create servings table")
    sql.append("CREATE TABLE IF NOT EXISTS public.servings (")
    sql.append("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    sql.append("    food_id UUID NOT NULL REFERENCES public.foods(id) ON DELETE CASCADE,")
    sql.append("    label TEXT NOT NULL,")
    sql.append("    grams NUMERIC NOT NULL,")
    sql.append("    unit_type TEXT NOT NULL,")
    sql.append("    quantity NUMERIC NOT NULL DEFAULT 1.0,")
    sql.append("    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),")
    sql.append("    CONSTRAINT uq_servings_food_label UNIQUE (food_id, label)")
    sql.append(");")
    sql.append("")
    sql.append("-- 4. Indexes for fast search and relations")
    sql.append("CREATE INDEX IF NOT EXISTS idx_foods_name ON public.foods (name);")
    sql.append("CREATE INDEX IF NOT EXISTS idx_foods_category ON public.foods (category);")
    sql.append("CREATE INDEX IF NOT EXISTS idx_foods_external_id ON public.foods (external_id);")
    sql.append("CREATE INDEX IF NOT EXISTS idx_food_nutrition_food_id ON public.food_nutrition (food_id);")
    sql.append("CREATE INDEX IF NOT EXISTS idx_servings_food_id ON public.servings (food_id);")
    sql.append("")
    sql.append("-- 5. Enable Row-Level Security (Public read access for catalog)")
    sql.append("ALTER TABLE public.foods ENABLE ROW LEVEL SECURITY;")
    sql.append("ALTER TABLE public.food_nutrition ENABLE ROW LEVEL SECURITY;")
    sql.append("ALTER TABLE public.servings ENABLE ROW LEVEL SECURITY;")
    sql.append("")
    sql.append("DROP POLICY IF EXISTS \"Foods are viewable by everyone\" ON public.foods;")
    sql.append("CREATE POLICY \"Foods are viewable by everyone\" ON public.foods FOR SELECT USING (true);")
    sql.append("")
    sql.append("DROP POLICY IF EXISTS \"Food nutrition is viewable by everyone\" ON public.food_nutrition;")
    sql.append("CREATE POLICY \"Food nutrition is viewable by everyone\" ON public.food_nutrition FOR SELECT USING (true);")
    sql.append("")
    sql.append("DROP POLICY IF EXISTS \"Servings are viewable by everyone\" ON public.servings;")
    sql.append("CREATE POLICY \"Servings are viewable by everyone\" ON public.servings FOR SELECT USING (true);")
    sql.append("")
    sql.append("-- 6. Authoritative Seed Data (USDA FoodData Central + ICMR-NIN IFCT 2017)")
    sql.append("DO $$")
    sql.append("DECLARE")
    sql.append("    fid UUID;")
    sql.append("BEGIN")

    for food in foods:
        name_esc = food["name"].replace("'", "''")
        cat_esc = food["category"].replace("'", "''")
        src_esc = food["source"].replace("'", "''")
        ext_esc = food["external_id"].replace("'", "''")
        brand_val = f"'{food['brand'].replace("'", "''")}'" if food.get("brand") else "NULL"
        def_unit_esc = food.get("default_unit", "portion").replace("'", "''")
        nut = food["nutrition"]
        micros_json = json.dumps(nut.get("micronutrients", {})).replace("'", "''")

        sql.append(f"    -- Item: {food['name']} ({food['external_id']})")
        sql.append(f"    INSERT INTO public.foods (id, name, category, source, external_id, brand, default_unit)")
        sql.append(f"    VALUES ('{food['id']}', '{name_esc}', '{cat_esc}', '{src_esc}', '{ext_esc}', {brand_val}, '{def_unit_esc}')")
        sql.append(f"    ON CONFLICT (external_id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category")
        sql.append(f"    RETURNING id INTO fid;")
        sql.append("")
        sql.append(f"    INSERT INTO public.food_nutrition (food_id, basis_grams, calories, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, micronutrients)")
        sql.append(f"    VALUES (fid, 100.0, {nut['calories']}, {nut['protein_g']}, {nut['carbs_g']}, {nut['fat_g']}, {nut['fiber_g']}, {nut['sugar_g']}, {nut['sodium_mg']}, '{micros_json}'::jsonb)")
        sql.append(f"    ON CONFLICT (food_id) DO UPDATE SET calories = EXCLUDED.calories, protein_g = EXCLUDED.protein_g, carbs_g = EXCLUDED.carbs_g, fat_g = EXCLUDED.fat_g, fiber_g = EXCLUDED.fiber_g;")
        sql.append("")

        for s in food["servings"]:
            lbl_esc = s["label"].replace("'", "''")
            unit_esc = s["unit_type"].replace("'", "''")
            sql.append(f"    INSERT INTO public.servings (id, food_id, label, grams, unit_type, quantity)")
            sql.append(f"    VALUES ('{s['id']}', fid, '{lbl_esc}', {s['grams']}, '{unit_esc}', {s['quantity']})")
            sql.append(f"    ON CONFLICT (food_id, label) DO UPDATE SET grams = EXCLUDED.grams, quantity = EXCLUDED.quantity;")

        sql.append("")

    sql.append("END $$;")
    sql.append("")

    migration_sql = "\n".join(sql)
    out_file = Path(__file__).resolve().parent.parent.parent.parent / "supabase" / "migrations" / "003_create_food_catalog.sql"
    out_file.write_text(migration_sql, encoding="utf-8")
    print(f"Generated {out_file} with {len(foods)} authoritative food records.")

if __name__ == "__main__":
    generate_catalog_migration()
